In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/train.csv")

In [4]:
df.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
df.shape

(1460, 81)

In [6]:
df.select_dtypes(include=['int64','float64']).columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [7]:
df.sample(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
852,853,75,RL,53.0,7128,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,8,2007,WD,Normal,164000
77,78,50,RM,50.0,8635,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,1,2008,WD,Normal,127000

In [8]:
x=df.drop("SalePrice", axis=1)
x

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

In [9]:
y=df["SalePrice"]

In [10]:
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [11]:
num_cols=x.select_dtypes(include=['int64','float64']).columns

In [12]:
print(num_cols)

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold'],
      dtype='object')

In [13]:
print(df.columns.tolist())

['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice']

In [14]:
print(x.shape)

(1460, 80)

In [15]:
missing=[col for col in num_cols if col not in x.columns]

In [16]:
print(missing)

[]

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x[num_cols]=scaler.fit_transform(x[num_cols])

In [18]:
print(type(num_cols))

<class 'pandas.core.indexes.base.Index'>

In [19]:
print((num_cols))

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold'],
      dtype='object')

In [20]:
x[num_cols].head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,-1.730865,0.073375,-0.208034,-0.207142,0.651479,-0.517200,1.050994,0.878668,0.510015,0.575425,...,0.351000,-0.752176,0.216503,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,0.138777
1,-1.728492,-0.872563,0.409895,-0.091886,-0.071836,2.179628,0.156734,-0.429577,-0.572835,1.171992,...,-0.060731,1.626195,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.489110,-0.614439
2,-1.726120,0.073375,-0.084449,0.073480,0.651479,-0.517200,0.984752,0.830215,0.322174,0.092907,...,0.631726,-0.752176,-0.070361,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.990891,0.138777
3,-1.723747,0.309859,-0.414011,-0.096897,0.651479,-0.517200,-1.863632,-0.720298,-0.572835,-0.499274,...,0.790804,-0.752176,-0.176048,4.092524,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,-1.367655
4,-1.721374,0.073375,0.574676,0.375148,1.374795,-0.517200,0.951632,0.733308,1.360826,0.463568,...,1.698485,0.780197,0.563760,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,2.100892,0.138777

In [21]:
x[num_cols].mean()

Id               0.000000e+00
MSSubClass      -8.455945e-17
LotFrontage     -2.677107e-16
LotArea         -5.840077e-17
OverallQual      1.387018e-16
OverallCond      3.540547e-16
YearBuilt        1.046347e-15
YearRemodAdd     4.496860e-15
MasVnrArea      -5.382900e-17
BsmtFinSF1      -2.433366e-17
BsmtFinSF2      -3.406712e-17
BsmtUnfSF       -6.600504e-17
TotalBsmtSF      2.457699e-16
1stFlrSF         6.509253e-17
2ndFlrSF        -1.825024e-17
LowQualFinSF     1.216683e-17
GrLivArea       -1.277517e-16
BsmtFullBath     2.311697e-17
BsmtHalfBath     2.433366e-17
FullBath         1.180182e-16
HalfBath         2.083569e-17
BedroomAbvGr     2.141362e-16
KitchenAbvGr     4.501726e-16
TotRmsAbvGrd    -1.022014e-16
Fireplaces      -4.866731e-18
GarageYrBlt      4.060888e-15
GarageCars       1.216683e-16
GarageArea      -1.216683e-17
WoodDeckSF       5.596741e-17
OpenPorchSF      3.041707e-17
EnclosedPorch   -2.311697e-17
3SsnPorch        4.866731e-18
ScreenPorch      5.475072e-17
PoolArea         1.946692e-17
MiscVal         -2.676702e-17
MoSold           7.543433e-17
YrSold           3.567436e-14
dtype: float64

In [59]:
x[num_cols].std()

Id               1.000343
MSSubClass       1.000343
LotFrontage      1.000417
LotArea          1.000343
OverallQual      1.000343
OverallCond      1.000343
YearBuilt        1.000343
YearRemodAdd     1.000343
MasVnrArea       1.000345
BsmtFinSF1       1.000343
BsmtFinSF2       1.000343
BsmtUnfSF        1.000343
TotalBsmtSF      1.000343
1stFlrSF         1.000343
2ndFlrSF         1.000343
LowQualFinSF     1.000343
GrLivArea        1.000343
BsmtFullBath     1.000343
BsmtHalfBath     1.000343
FullBath         1.000343
HalfBath         1.000343
BedroomAbvGr     1.000343
KitchenAbvGr     1.000343
TotRmsAbvGrd     1.000343
Fireplaces       1.000343
GarageYrBlt      1.000363
GarageCars       1.000343
GarageArea       1.000343
WoodDeckSF       1.000343
OpenPorchSF      1.000343
EnclosedPorch    1.000343
3SsnPorch        1.000343
ScreenPorch      1.000343
PoolArea         1.000343
MiscVal          1.000343
MoSold           1.000343
YrSold           1.000343
dtype: float64

In [60]:
from sklearn.preprocessing import OrdinalEncoder

In [76]:
quality_order=[
    [
        'Po','Fa',"TA","Gd","Ex" 
    ]
]

In [77]:
encoder=OrdinalEncoder(categories=quality_order)

In [78]:
df['ExterQual']=encoder.fit_transform(df[["ExterQual"]])

ValueError: could not convert string to float: 'Po'

In [ ]:
df['ExterQual'].head()

0    3.0
1    2.0
2    3.0
3    2.0
4    3.0
Name: ExterQual, dtype: float64

In [ ]:
df['ExterQual']=df['ExterQual'].fillna("TA")

In [ ]:
df.select_dtypes(include='object').columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd',
       'MasVnrType', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [ ]:
df["Neighborhood"].unique()

KeyError: 'Neighborhood'

In [79]:
from sklearn.preprocessing import OneHotEncoder

In [80]:
df.isnull().sum()

Id                        0
MSSubClass                0
MSZoning                  0
LotFrontage             259
LotArea                   0
                       ...
Neighborhood_SawyerW      0
Neighborhood_Somerst      0
Neighborhood_StoneBr      0
Neighborhood_Timber       0
Neighborhood_Veenker      0
Length: 130, dtype: int64

In [81]:
df['Neighborhood']

KeyError: 'Neighborhood'

In [82]:
df.shape

(1460, 130)

In [83]:
encoder=OneHotEncoder(handle_unknown='ignore',sparse_output=False);

In [84]:
encoded=encoder.fit_transform(df[["Neighborhood"]])

KeyError: "None of [Index(['Neighborhood'], dtype='object')] are in the [columns]"

In [85]:
print(encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [86]:
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out(["Neighborhood"]))

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [87]:
print(encoded.shape)

(1460, 25)

In [88]:
encoder.get_feature_names_out(["Neighborhood"])

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [89]:
df = pd.concat([df, encoded_df], axis=1)

In [90]:
df.drop("Neighborhood", axis=1, inplace=True)

KeyError: "['Neighborhood'] not found in axis"

In [91]:
num_cols = [
    "LotArea",
    "GrLivArea",
    "OverallQual"
]

In [93]:
df.select_dtypes(include='object').columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd',
       'MasVnrType', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [94]:

df["Street"].value_counts()

Street
Pave    1454
Grvl       6
Name: count, dtype: int64

In [95]:
from sklearn.compose import ColumnTransformer

In [96]:
num_cols = ["LotArea", "GrLivArea", "GarageArea"]

In [98]:
nominal_cols = ["Street"]

In [99]:
ordinal=["KitchenQual"]

In [100]:
quality_order = [["Po", "Fa", "TA", "Gd", "Ex"]]

In [103]:
transformer=ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),
        ("ord", OrdinalEncoder(categories=quality_order), ordinal),
        ("nom", OneHotEncoder(handle_unknown="ignore"),nominal_cols)
    ],
    remainder='passthrough'
)

In [105]:
x_transformed = transformer.fit_transform(x)

In [106]:
print(x_transformed)

[[-0.2071417077743113 0.37033343921677997 0.351000320866527 ...
  0.1387774889497933 'WD' 'Normal']
 [-0.09188637231949033 -0.4825119145852412 -0.06073101261530329 ...
  -0.6144386220786311 'WD' 'Normal']
 [0.07347997855047018 0.5150125617367657 0.631726230058684 ...
  0.1387774889497933 'WD' 'Normal']
 ...
 [-0.14781026552278606 1.5696472180008723 -1.0339141644814478 ...
  1.6452097110066422 'WD' 'Normal']
 [-0.08016039471234768 -0.8327876848967856 -1.090059346319879 ...
  1.6452097110066422 'WD' 'Normal']
 [-0.05811154792968627 -0.49393395057366113 -0.9216238008045848 ...
  0.1387774889497933 'WD' 'Normal']]

In [108]:
feature_names = transformer.get_feature_names_out()
print(feature_names)

['num__LotArea' 'num__GrLivArea' 'num__GarageArea' 'ord__KitchenQual'
 'nom__Street_Grvl' 'nom__Street_Pave' 'remainder__Id'
 'remainder__MSSubClass' 'remainder__MSZoning' 'remainder__LotFrontage'
 'remainder__Alley' 'remainder__LotShape' 'remainder__LandContour'
 'remainder__Utilities' 'remainder__LotConfig' 'remainder__LandSlope'
 'remainder__Neighborhood' 'remainder__Condition1' 'remainder__Condition2'
 'remainder__BldgType' 'remainder__HouseStyle' 'remainder__OverallQual'
 'remainder__OverallCond' 'remainder__YearBuilt' 'remainder__YearRemodAdd'
 'remainder__RoofStyle' 'remainder__RoofMatl' 'remainder__Exterior1st'
 'remainder__Exterior2nd' 'remainder__MasVnrType' 'remainder__MasVnrArea'
 'remainder__ExterQual' 'remainder__ExterCond' 'remainder__Foundation'
 'remainder__BsmtQual' 'remainder__BsmtCond' 'remainder__BsmtExposure'
 'remainder__BsmtFinType1' 'remainder__BsmtFinSF1'
 'remainder__BsmtFinType2' 'remainder__BsmtFinSF2' 'remainder__BsmtUnfSF'
 'remainder__TotalBsmtSF' 'remainder__Heating' 'remainder__HeatingQC'
 'remainder__CentralAir' 'remainder__Electrical' 'remainder__1stFlrSF'
 'remainder__2ndFlrSF' 'remainder__LowQualFinSF' 'remainder__BsmtFullBath'
 'remainder__BsmtHalfBath' 'remainder__FullBath' 'remainder__HalfBath'
 'remainder__BedroomAbvGr' 'remainder__KitchenAbvGr'
 'remainder__TotRmsAbvGrd' 'remainder__Functional' 'remainder__Fireplaces'
 'remainder__FireplaceQu' 'remainder__GarageType' 'remainder__GarageYrBlt'
 'remainder__GarageFinish' 'remainder__GarageCars' 'remainder__GarageQual'
 'remainder__GarageCond' 'remainder__PavedDrive' 'remainder__WoodDeckSF'
 'remainder__OpenPorchSF' 'remainder__EnclosedPorch'
 'remainder__3SsnPorch' 'remainder__ScreenPorch' 'remainder__PoolArea'
 'remainder__PoolQC' 'remainder__Fence' 'remainder__MiscFeature'
 'remainder__MiscVal' 'remainder__MoSold' 'remainder__YrSold'
 'remainder__SaleType' 'remainder__SaleCondition']