In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/train.csv")

In [3]:
df["LotArea"].describe()

count      1460.000000
mean      10516.828082
std        9981.264932
min        1300.000000
25%        7553.500000
50%        9478.500000
75%       11601.500000
max      215245.000000
Name: LotArea, dtype: float64

In [4]:
df["LotArea_Bin"] = pd.cut(
    df["LotArea"],
    bins=4
)

In [6]:
df[["LotArea", "LotArea_Bin"]].tail()

      LotArea           LotArea_Bin
1455     7917  (1086.055, 54786.25]
1456    13175  (1086.055, 54786.25]
1457     9042  (1086.055, 54786.25]
1458     9717  (1086.055, 54786.25]
1459     9937  (1086.055, 54786.25]

In [7]:
df["LotArea_Bin"] = pd.cut(
    df["LotArea"],
    bins=4,
    labels=["Small", "Medium", "Large", "Very Large"]
)

In [11]:
df[["LotArea", "LotArea_Bin"]].tail()

      LotArea LotArea_Bin
1455     7917       Small
1456    13175       Small
1457     9042       Small
1458     9717       Small
1459     9937       Small

In [12]:
df["LotArea_QBin"] = pd.qcut(
    df["LotArea"],
    q=4
)

In [13]:
from sklearn.preprocessing import Binarizer

In [14]:
binarizer = Binarizer(threshold=1)

In [15]:
df["GarageCars_Binary"] = binarizer.fit_transform(
    df[["GarageCars"]]
)

In [16]:
df["GrLivArea_bin"]=pd.cut(
    df["GrLivArea"],
    bins=4,
    labels=["Small","Medium","Large","Very Large"]

)

In [18]:
df["GrLivArea_bin"].tail()

1455     Small
1456    Medium
1457    Medium
1458     Small
1459     Small
Name: GrLivArea_bin, dtype: category
Categories (4, object): ['Small' < 'Medium' < 'Large' < 'Very Large']

In [19]:
from sklearn.preprocessing import KBinsDiscretizer

In [20]:
kbin = KBinsDiscretizer(
    n_bins=4,
    encode="ordinal",
    strategy="uniform"
)

In [21]:
df["GrLivArea_KBin"] = kbin.fit_transform(
    df[["GrLivArea"]]
)

In [22]:
df[["GrLivArea", "GrLivArea_KBin"]].head(10)

   GrLivArea  GrLivArea_KBin
0       1710             1.0
1       1262             0.0
2       1786             1.0
3       1717             1.0
4       2198             1.0
5       1362             0.0
6       1694             1.0
7       2090             1.0
8       1774             1.0
9       1077             0.0