In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/train.csv")

In [3]:
df_indicator = df.copy()

In [4]:
df_indicator["LotFrontage_missing"] = df_indicator["LotFrontage"].isnull().astype(int)

In [5]:
df_indicator["LotFrontage"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
1455    False
1456    False
1457    False
1458    False
1459    False
Name: LotFrontage, Length: 1460, dtype: bool

In [6]:
df_indicator[["LotFrontage", "LotFrontage_missing"]].head(10)

   LotFrontage  LotFrontage_missing
0         65.0                    0
1         80.0                    0
2         68.0                    0
3         60.0                    0
4         84.0                    0
5         85.0                    0
6         75.0                    0
7          NaN                    1
8         51.0                    0
9         50.0                    0

In [7]:
df_indicator["LotFrontage_missing"].value_counts()

LotFrontage_missing
0    1201
1     259
Name: count, dtype: int64

In [15]:
from sklearn.impute import MissingIndicator
import pandas as pd

indicator = MissingIndicator(features="missing-only")

missing_features = indicator.fit_transform(df)

print(missing_features.shape)

missing_df = pd.DataFrame(
    missing_features,
    columns=df.columns[indicator.features_]
)

missing_df.head()

(1460, 19)

,LotFrontage,Alley,MasVnrType,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond,PoolQC,Fence,MiscFeature
0,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True
1,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
2,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
3,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
4,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True

In [16]:
df_indicator = pd.concat(
    [df, missing_df],
    axis=1
)

In [17]:
df_indicator

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Electrical,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond,PoolQC,Fence,MiscFeature
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,True,True,True
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,True,True,True
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,True,True,True
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,True,True,True
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,True,True,True
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,True,False,True
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,True,False,False
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,True,True,True
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,True,True,True

AttributeError: 'MissingIndicator' object has no attribute 'shape'